### ISSUE TITLE
strange behavior on imports merge

### ISSUE THREAD

**Issue by themetalone** [EastWindShak/tsm#5]
During testing I found a bug concerning imports: 

base: 
````
import { thit as that } from "somewhere";
````

patch:
````
import { thet as thot } from "somewherelse";
````
results in
````
import { that } from 'somewhere';
import { thet as thot } from "somewhereelse";
````

It seems that there is some unwanted refactoring on the base imports but not on the patch imports. 

Test cases incoming with future pr

**Comment by EastWindShak** [comment]
This issue was moved to EastWindShak/ts-merger#4
