### ISSUE TITLE
missing patch import

### ISSUE THREAD

**Issue by themetalone** [EastWindShak/tsm#8]
Found another one. I'm not sure if it related to #5.

base:
````
import { a } from 'c';
````
patch:
````
import { b } from 'c';
````
result
````
import { a } from 'c';
````

but shouldn't it be 
````
import { a, b } from 'c';
````

**Comment by EastWindShak** [comment]
this should be the normal behaviour. Maybe the refactor process broke it. I'll check

**Comment by EastWindShak** [comment]
This issue was moved to EastWindShak/ts-merger#1
